### ISSUE TITLE
US- Operaciones en la óptica.

### ISSUE THREAD

**Issue by Tatiana-Urbina** [marioG130/ISPC-FullStack-2022#3]

**Comment by Tatiana-Urbina** [comment]
**como** usuario
**quiero** consultar las últimas operaciones realizadas en la óptica.
**para** conocer el estado de la misma.
Requerimientos:
El sistema debe almacenar la fecha y monto de los productos encargados o pedidos por el usuario.
El sistema enviará la información de las últimas operaciones al correo electrónico establecido por el usuario.
Criterios de Aceptación:
dado un usuario que ha realizado compras o ventas de los productos de la óptica
cuando realice las operaciones el sistema guardará la información (fecha, cantidad, precio, forma de pago)
entonces el usuario podrá solicitar dicha información.

**Comment by marioG130** [comment]
Duplicada
